language: android
sudo: false
addons:
  apt:
    packages:
    - xvfb
jdk:
  - openjdk7
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
  - export CHROME_BIN=chromium-browser
  - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
  - export ANDROID_HOME=/usr/local/android-sdk
  - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - . $HOME/.nvm/nvm.sh
  - nvm install 4
  - nvm use 4
  - npm install
script: "make test"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
